CREATE TABLE FMVV_SYNC(id INTEGER PRIMARY KEY AUTOINCREMENT, id_server INTEGER, classname TEXT NOT NULL);
INSERT INTO FMVV_SYNC (id, classname) VALUES (1000000000, 'offsetval');
CREATE TABLE FMVV_TO_SYNC(id INTEGER PRIMARY KEY, id_user INTEGER NOT NULL, classname TEXT NOT NULL, action INTEGER NOT NULL);