CREATE TABLE tb_document(id INTEGER PRIMARY KEY AUTOINCREMENT,id_author INTEGER,text TEXT NOT NULL,title TEXT NOT NULL,created_at TIMESTAMP NOT NULL);
CREATE TABLE tb_score(id INTEGER PRIMARY KEY AUTOINCREMENT,id_author INTEGER NOT NULL,id_document INTEGER NOT NULL,score INTEGER);
CREATE TABLE tb_customer_join_document(id_customer INTEGER PRIMARY KEY AUTOINCREMENT,id_document INTEGER NOT NULL);
CREATE TABLE tb_customer(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL);
CREATE TABLE tb_author(id INTEGER PRIMARY KEY AUTOINCREMENT,active BOOLEAN,name TEXT NOT NULL,created_at TIMESTAMP NOT NULL);
